import { NextResponse } from 'next/server';

export async function GET() {
    const productList = [
        {
            trading_company: "三ツ星ファーム",
            product_name: "濃厚トマトソースとチーズの贅沢ハンバーグ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_01.jpg"
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "ナポリの風香る チーズをまとったトマトチキン",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_02.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "プリッと甘旨 特製海老マヨ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_03.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "幸せタルタルの国産サーモンフライ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_04.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "蝦醤香る特製エビのチリソース煮",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_05.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "濃厚トマトチーズソースの蟹クリームコロッケ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_06.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "彩り野菜とスパイシーケイジャンチキン",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_07.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "トリュフ香る デミグラスのハンバーグ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_08.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "ねぎ塩うまだれチキン竜田揚げ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_09.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "とろーりタイ風コク旨ガパオ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_010.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "たっぷりタルタル 国産鶏肉のチキン南蛮",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_011.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "丹波の西京味噌の銀鮭焼き弁当",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_012.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "コクと旨味のオニオンソースのハンバーグ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_013.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "海老とチキンの幸せほっこりグラタン",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_014.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "レモンバターのやみつきローストチキン",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_015.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "タンドリー風スパイスチキン",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_016.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "ナスとほうれん草のこんがりラザニア",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_017.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "柚子風味 ジューシー豚しゃぶ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_018.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "旨々ホイコーローと定番中華の味セット",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_019.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "香ばし醤油の特製豚肉の生姜焼き",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_020.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "イカと揚げ茄子のピリ辛チリソース",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_021.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "香ばしカレイの唐揚げユーリンソース",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_022.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "白身魚の甘辛特製黒酢あん",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_023.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "鰹と昆布の旨みひろがるほくほく牛肉じゃが",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_024.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "三ツ星名店のナポリ風ピッツァ（マルゲリータ）",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_025.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "あと一口がとまらない 牛の旨味チャプチェ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_026.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "定番の味しみしみぶり大根",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_027.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "特製タレで漬け込んだ やみつき鶏天弁当",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_028.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "チーズのコク深い 鶏と野菜のクリームソースかけ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_029.jpg"
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "瀬戸内産レモン香る ふんわりカツ煮",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_030.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "こだわり唐揚げと彩り野菜の油淋鶏",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_031.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "赤ワインと黒胡椒の大人のデミハンバーグ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_032.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "牛肉の胡麻ポン蒸し焦がし葱を添えて",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_033.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "ほっこり味わい 赤魚と豆腐の寄せ煮",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_034.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "ガッツリ満足 背徳のペペロンチーノ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_035.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "満腹ソーセージと鱈フライ 特製タルタル乗せ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_036.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "ロールキャベツのやさしさ豆乳スープ仕立て",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_037.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "鶏と味染みナスのさっぱりみぞれあん",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_038.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "国産柚子が香る 魚介の八宝菜",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_039.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "コク旨豚キムチ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_040.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "濃厚ゴマだれの担々風ハンバーグ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_041.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "もち麦入りチリソースたっぷりハンバーグ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_042.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "プリプリ鱈の香草パン粉焼きチーズソース",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_043.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "じっくり香ばしく焼き上げた牛カルビライスバーガー",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_044.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "黒酢とりんご酢の優しい甘さのマンゴー酢豚",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_045.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "天津風卵の贅沢紅ズワイガニの白雲あん",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_046.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "ごはんがすすむド定番甘辛鶏照り焼き",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_047.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "国産柚子香る 和風おろしハンバーグ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_048.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "鈴なり 割烹の鮭と蓮根の照り煮",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_049.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "豚肉とかぼちゃのうま辛白みそダレ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_050.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "やさしさ奏でるさつま芋のシュクメルリ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_051.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "鶏つくねあおさ香るとろ～りチーズクリーム",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_052.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "ポルチーニの芳醇な香り 大人のグラタン",
            "price":200,
            company_id: 1,
            img: "/product_imag/product_053.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "三ツ星名店のナポリ風ピッツァ（クワトロフォルマッジ）",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_054.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "ヒレカツ濃厚Wチーズソース",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_055.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "じっくり煮詰めた 本格バターチキンカレー",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_056.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "牛の旨味染みわたる キーマカレー",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_057.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "カレイのムニエル ジェノベーゼソース",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_058.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "ローストチキン スパイスバターのカリー仕立て",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_059.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "和風だしポン酢が決め手 たっぷり野菜の牛おろし",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_060.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "鈴なり 白身魚の和風梅ソースとお野菜のおばんざい",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_061.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "ミートボール はちみつ甘酢あんかけ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_062.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "お肉と野菜コロコロ 中華屋さんの定番酢豚",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_063.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "ビストロ風トマトが入ったハッシュドビーフ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_064.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "プリプリ赤魚の和風みぞれあんかけ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_065.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "カナダ名物 チーズポテトとチキンボール",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_066.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "芳香デミグラスの深いコク 大人の洋風もつ煮",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_067.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "魚介のコクと旨みの海鮮チゲ風",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_068.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "マッシュルームソースの洋風チキンカツ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_069.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "ふんわり豆腐ハンバーグ 香味ネギソース",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_070.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "鶏の旨揚げ 具だくさんタルタルサラダ仕立て",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_071.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "海老カツと濃厚エビトマトクリームのW仕立て",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_072.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "鈴なり 割烹の鶏肉と大根の葱生姜だれ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_073.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "鶏ともち麦の濃厚チーズリゾット",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_074.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "さっぱり豚もも肉胡麻豆乳だれ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_075.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "スペイン風オムレツとミートボールしらすのトマトチーズソース",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_076.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "九条ねぎと鶏肉の塩だれスープ煮",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_077.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "旨辛がたまらない 韓国風チーズトッポギ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_078.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "鈴なり 割烹の豚肉とめかぶのネバトロあんかけ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_079.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "赤ワインでコクを出したご褒美トマトすき煮",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_080.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "背徳感がたまらないホルモン焼き",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_081.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "白身フライのつぶつぶたらこマヨソース",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_082.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "しにせの京なま麩湯葉あんかけ仕立て",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_083.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "とろ～りたまごのふわとろ親子煮",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_084.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "カチャトーラ風トマトチキン",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_085.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "韓国で話題 「ロゼ」ソースの蒸し餃子",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_086.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "しっとり蒸し鶏の魅惑のバンバンジー",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_087.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "台湾夜市の味わいルーローハン弁当",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_088.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "しっとり蒸し鶏の洋風チーズソース",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_089.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "3種のチーズのカルボナーラ風 ハンバーグ",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_090.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "香ばしグリルチキンのハニーマスタード",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_091.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "６種の具材が入った中華丼の具",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_092.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "タイ風春雨の炒めもの",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_093.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "デミ&ホワイト ハンバーグ2種のソース",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_094.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "スペイン風ほっこりブイヤベース",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_095.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "蟹とふわふわ卵のプーパッポンカレー",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_096.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "ベトナム屋台のお好み焼き バインセオ風",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_097.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "ビーフストロガノフセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_098.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "デミグラスハンバーグ＆チキンセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_099.jpg"
        },
        {
            trading_company: "マッスルデリ",
            product_name: "スパイシータンドリーチキンセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0100.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "チキン南蛮セット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0101.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "チーズとトマトのタコミートセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0102.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "オニオンソースハンバーグセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0103.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "やわらかヒレカツ丼セット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0104.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "とろとろ卵のオムライスセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0105.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "長崎ちゃんぽんセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0106.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "中華そぼろ丼セット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0107.jpg",
        },
        {
            trading_company: "マッスルデリ", 
            product_name: "コクうま豚の生姜焼きセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0108.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "柚子胡椒かおるツナと竹輪のパスタセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0109.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "豚もも肉のスタミナ炒めセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0110.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "海鮮あんかけ焼きそばセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0111.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "具だくさんトムヤムセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0112.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "イタリアンチキンステーキセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0113.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "デミグラス仕立てのボロネーゼセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0114.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "照り焼きチキンセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0115.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "鶏肉の柔らか塩麹焼きセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_011.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "チーズキーマカレーセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0117.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "チキンたっぷりカレーセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0118.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "ガパオライスセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0119.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "とろっと玉子の親子丼セット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0120.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "鶏つくねと上海風焼きそばセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0121.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "ジェノベーゼパスタセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0122.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "甘辛ダレの鶏の生姜焼きセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0123.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "回鍋肉セット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0124.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "香味野菜香るよだれ鶏セット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0125.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "豚もも肉のデミトマトソースセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0126.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "旨辛ビビンバセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0127.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "ピリ辛鶏チーズキムチセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0128.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "レモン風味のローストチキンセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0129.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "ふっくら赤魚の西京焼きセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0130.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "さばのみそ煮セット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0131.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "カオマンガイセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0132.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "鶏肉のローストクリームソースセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0133.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "鶏肉のマスタード焼きセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0134.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "鶏肉豆腐ハンバーグセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0135.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "ルーロー飯セット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0136.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "ナポリタンセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0137.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "鶏ささみの梅大葉焼きセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0138.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "彩りチンジャオロースセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0139.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "サーモンとアスパラのパスタセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0140.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "鶏肉のチリソースセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0141.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "鶏肉のオイスターソースがけセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0142.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "チンジャオロース焼きそばセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0143.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "魚介のトマトパスタセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0144.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "赤魚の煮つけセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0145.jpg",
        },
        {
            trading_company: "マッスルデリ",
            product_name: "ほっけ焼きセット",
            price: 300,
            company_id: 2,
            img: "/product_imag/product_0146.jpg",
        },
        {
            trading_company: "三ツ星ファーム",
            product_name: "とろふわ卵のフレンチ風照り焼きチキン",
            price: 200,
            company_id: 1,
            img: "/product_imag/product_0147.jpg",
        },
    ];

    return NextResponse.json(productList);
}

