import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "弁当管理アプリ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        {children}
      </body>
    </html>
  );
}
